name: "Publish module"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Build and publish to the Forge"
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_release.yml@main"
    secrets: "inherit"
